name: 'Check IntelliTect.Coalesce'
description: 'Make sure coalesce has been run'
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  working-directory:
    description: 'Working directory'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Ensure Coalesce has been run
      shell: pwsh
      run: |
        echo 'Running Coalesce'
        dotnet -d coalesce
        if ($LASTEXITCODE -ne 0) { throw "`dotnet coalesce` exited with code $LASTEXITCODE" }
        echo 'Adding Changed Files'
        git add .
        echo 'Checking Diff'
        git diff HEAD --cached --exit-code
      working-directory: ${{ inputs.working-directory }}
